name: 'id_stitching'
version: '1.1.2'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  id-columns: ('anonymous_id', 'user_id', 'email', 'context_traits_email')
  ids-to-exclude: ('sources','testuser@rudderstack.com', 'sss@ggg.com')
  schemas-to-include: ()
  schemas-to-exclude: ()
  tables-to-include: ()
  tables-to-exclude: ()
